main:
  - name: 首页
    url: /
    weight: 1
  - name: 精选
    url: /feed/
    weight: 2
  - name: 功能
    url: /#features
    weight: 3
  - name: 体验
    url: /#demo
    weight: 4
  - name: 架构
    url: /#architecture
    weight: 5
  - name: 登录
    url: /login/
    weight: 6
